# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Check' do

end

target 'Check_Library_Tests' do

end

target 'Check_Application_Tests' do

end


pod 'ParseFacebookUtils', :podspec => 'https://raw.githubusercontent.com/rickerbh/ParseFacebookUtilsSpec/master/ParseFacebookUtils.podspec.json'
